"""Regression guard for the classical operator-code SUT executable conservation
verdict (increment 2 / claim C34).

The artifact is generated by tools/run_classical_operator_conservation.py during
cloud execution (pure numpy, no GPU / sibling repo). Until it exists this test
skips, keeping the local suite green; once the cloud run commits the artifact the
guard validates it and pins the honest numbers so prose cannot overstate them.

See paper/39_increment2_classical_operator_sut_design.md.
"""
from __future__ import annotations

import json
import unittest
from pathlib import Path

ROOT = Path(__file__).resolve().parents[1]
LEDGER = ROOT / "research_assets/runs/classical-operator-conservation/raw/metric_ledger.json"
CLAIM_LEDGER = ROOT / "research_assets/experiments/claim-ledger.yml"


@unittest.skipUnless(
    LEDGER.exists(),
    "classical-operator-conservation artifact not generated yet (run the tool in the cloud)",
)
class ClassicalOperatorConservationTest(unittest.TestCase):
    def setUp(self) -> None:
        self.d = json.loads(LEDGER.read_text(encoding="utf-8"))

    def test_conservation_mr_is_admissible(self) -> None:
        mr = self.d["conservation_mr"]
        self.assertTrue(mr["admissible"])
        self.assertLessEqual(mr["tolerance"], 1e-9)  # a tight, machine-precision-scale tolerance

    def test_baseline_conserves_to_machine_precision(self) -> None:
        s = self.d["summary"]
        self.assertTrue(s["baseline_pass"])
        self.assertLess(s["baseline_max_abs_delta_mass"], self.d["conservation_mr"]["tolerance"])

    def test_all_operator_code_faults_are_detected(self) -> None:
        s = self.d["summary"]
        self.assertGreaterEqual(s["num_faults"], 3)
        self.assertEqual(s["faults_detected"], s["num_faults"])

    def test_three_task_typed_verdict_contrast(self) -> None:
        tv = self.d["typed_verdict_contrast"]
        self.assertIn("executable", tv["classical_fv_operator"].lower())
        self.assertIn("deferred", tv["cylinder_mgn"].lower())
        self.assertIn("rejected", tv["airfoil_mgn"].lower())

    def test_claim_c34_registered(self) -> None:
        # The cloud integration step adds C34 with the real numbers from this run.
        self.assertIn("C34", CLAIM_LEDGER.read_text(encoding="utf-8"))


if __name__ == "__main__":
    unittest.main()
