"""Orchestrate E1: run each of 6 MR runners against each of the 6 SUTs in the
multi-checkpoint robustness study and aggregate per-MR distributions.

SUT roster (defined in docs/superpowers/plans/2026-06-06-empirical-enhancement-E1E2E3.md):
- S0..S3 = base config (hidden=64, layers=4), training seeds {0,1,2,3} — seed-replica family;
- S4    = hidden=128, seed 0 — wide variant;
- S5    = num_layers=6, seed 0 — deep variant.

Runs all 6 MR runners per SUT, then aggregates per-MR key metrics. Bootstrap 95% CI is
reported across S0..S3 (the seed-replica family); S4 / S5 are reported descriptively
(single-instance config variants).

Honesty boundary: the K=6 checkpoints share one architecture family and one dataset; this
is a cross-checkpoint/cross-configuration robustness study, not a cross-SUT generalization
claim. The Minimum-MR-SubSet repo is read-only; all manifests and outputs land here.
"""
from __future__ import annotations

import argparse
import hashlib
import json
import shutil
import subprocess
import sys
from pathlib import Path

ROOT = Path("/home/user/Domain-Validity-Gated-MR-for-SciML")
MC = ROOT / "research_assets/runs/multicheckpoint"
S0_CKPT = ROOT / "research_assets/runs/real-sut-node-permutation-pilot/sut/checkpoint.pt"
SOURCE_CASE = "research_assets/runs/real-sut-node-permutation-pilot/source_case.npz"

SUTS = [
    ("S0", "base config, seed 0", S0_CKPT),
    ("S1", "base config, seed 1", MC / "S1/checkpoint.pt"),
    ("S2", "base config, seed 2", MC / "S2/checkpoint.pt"),
    ("S3", "base config, seed 3", MC / "S3/checkpoint.pt"),
    ("S4", "hidden=128, seed 0", MC / "S4/checkpoint.pt"),
    ("S5", "num_layers=6, seed 0", MC / "S5/checkpoint.pt"),
]

# (runner_id, runner_module, ledger_relpath, manifest_extras, runner_extra_args)
RUNNERS = [
    ("node_perm", "run_real_sut_mr",
     "raw/metric_ledger.json",
     {"mr_id": "mgn-node-permutation-equivariance"},
     ["--frame", "0"]),
    ("mirror_ood", "run_mirror_y_ood_stress",
     "raw/metric_ledger.json",
     {"mr_id": "mgn-mirror-y-equivariance",
      "mirror_axis": "0.205", "ratio_threshold": "2.0"},
     ["--frames", "0,4"]),
    ("mirror_sym", "run_mirror_y_symmetric_mesh",
     "raw/metric_ledger.json",
     {"mr_id": "mgn-mirror-y-equivariance-exact-symmetric-mesh",
      "nx": "48", "half_rows": "20", "Lx": "1.6", "Ly": "0.4",
      "no_source_case": True},
     []),
    ("conservation", "run_conservation_diagnostic",
     "raw/metric_ledger.json",
     {"mr_id": "mgn-discrete-divergence-boundedness",
      "regression_threshold": "1.5", "absolute_divergence_tol": "1e-6"},
     ["--frames", "0,4"]),
    ("rollout", "run_rollout_accuracy",
     "raw/metric_ledger.json",
     {"mr_id": "rollout-accuracy-diagnostic"},
     []),
    ("fault_det", "run_seeded_fault_detection",
     "raw/metric_ledger.json",
     {"mr_id": "seeded-fault-detection-by-domain-validity-mrs"},
     []),
]


def sha256_of(p: Path) -> str:
    return hashlib.sha256(p.read_bytes()).hexdigest()


def build_manifest(sut_id: str, ckpt: Path, runner_id: str, mod: str,
                   extras: dict, runner_args: list[str]) -> Path:
    rel_ckpt = ckpt.relative_to(ROOT).as_posix()
    rdir = MC / sut_id / runner_id
    rdir.mkdir(parents=True, exist_ok=True)
    raw_dir = rdir / "raw"
    raw_dir.mkdir(exist_ok=True)
    manifest_path = rdir / "manifest.yml"
    no_src = extras.pop("no_source_case", False)

    fields: dict[str, str] = {
        "record_type": "real-sut-run",
        "run_id": f"e1-mc-{sut_id}-{runner_id}-001",
        "sut_id": "cylinder_flow_meshgraphnet",
        "sut_repo": "/home/user/Minimum-MR-SubSet",
        "sut_commit": "8c0b7ef3605fd9452884d701e2a191a2b14a5a35",
        "checkpoint_path": rel_ckpt,
        "checkpoint_sha256": sha256_of(ckpt),
        "dataset_root": "/home/user/Minimum-MR-SubSet/data/raw/cylinder_flow_deepmind",
        "raw_output_dir": (rdir / "raw").relative_to(ROOT).as_posix(),
        "seed": "20260606",
        "device": "cpu",
        "python_version": sys.version.split()[0],
        "framework_version": "torch 2.12.0+cpu",
        "command": (f"python3 -B tools/{mod}.py --manifest "
                    f"{manifest_path.relative_to(ROOT).as_posix()}"
                    + (" " + " ".join(runner_args) if runner_args else "")),
    }
    if not no_src:
        fields["source_case_path"] = SOURCE_CASE
    fields.update({k: str(v) for k, v in extras.items()})

    lines = [f'# E1 multi-checkpoint manifest: SUT {sut_id} x runner {runner_id}',
             f'# Generated by tools/e1_multicheckpoint_runner.py']
    for k, v in fields.items():
        lines.append(f'{k}: "{v}"')
    manifest_path.write_text("\n".join(lines) + "\n", encoding="utf-8")
    return manifest_path


def run_runner(mod: str, manifest: Path, args: list[str]) -> tuple[int, str]:
    cmd = [sys.executable, "-B", str(ROOT / f"tools/{mod}.py"),
           "--manifest", str(manifest)] + list(args)
    proc = subprocess.run(cmd, cwd=ROOT, capture_output=True, text=True, timeout=900)
    return proc.returncode, (proc.stdout + proc.stderr)[-2000:]


def extract_metric(runner_id: str, ledger_path: Path) -> dict:
    """Pull the key metric(s) from a runner's ledger into a uniform record."""
    if not ledger_path.exists():
        return {"ok": False, "error": "no_ledger"}
    d = json.loads(ledger_path.read_text())
    if runner_id == "node_perm":
        e = d.get("entries", [])
        if not e:
            return {"ok": False, "error": "no_entry"}
        return {"ok": True, "rel_l2": e[0]["metric_value"],
                "verdict": e[0]["verdict"]}
    if runner_id == "mirror_ood":
        e = d.get("entries", [])
        v = [x["metric_value"] for x in e]
        vof = [x.get("violation_over_floor") for x in e]
        verdicts = [x["verdict"] for x in e]
        return {"ok": True, "rel_l2_per_frame": v, "violation_over_floor": vof,
                "verdicts": verdicts,
                "median_rel_l2": float(sorted(v)[len(v)//2]) if v else None,
                "precondition_decision": d.get("precondition_decision")}
    if runner_id == "mirror_sym":
        return {"ok": True, "rel_l2": d.get("metric_value"),
                "verdict": d.get("verdict"),
                "normalizer_control": d.get("normalizer_equivariance_control")}
    if runner_id == "conservation":
        e = d.get("entries", [])
        ratios = [x.get("ratio_interior") for x in e]
        verdicts = [x["verdict"] for x in e]
        return {"ok": True, "ratio_interior_per_frame": ratios,
                "verdicts": verdicts,
                "max_ratio": max([r for r in ratios if r is not None], default=None)}
    if runner_id == "rollout":
        t = d.get("transitions", [])
        rl2 = [x.get("relative_l2") for x in t]
        rl2 = [x for x in rl2 if x is not None]
        rl2_sorted = sorted(rl2)
        return {"ok": True, "rel_l2_per_transition": rl2,
                "median": (rl2_sorted[len(rl2_sorted)//2] if rl2_sorted else None),
                "mean": (sum(rl2_sorted)/len(rl2_sorted) if rl2_sorted else None)}
    if runner_id == "fault_det":
        det = d.get("detection_matrix", {})
        summary = d.get("summary", {})
        return {"ok": True, "detection_matrix": det, "summary": summary}
    return {"ok": False, "error": "unknown_runner"}


def bootstrap_ci(values: list[float], n: int = 2000, alpha: float = 0.05) -> tuple[float, float, float]:
    import random
    if not values:
        return (float("nan"),) * 3
    rng = random.Random(20260606)
    mean = sum(values) / len(values)
    boots: list[float] = []
    for _ in range(n):
        s = [values[rng.randrange(len(values))] for _ in values]
        boots.append(sum(s) / len(s))
    boots.sort()
    lo = boots[int(n * alpha / 2)]
    hi = boots[int(n * (1 - alpha / 2))]
    return mean, lo, hi


def main() -> int:
    ap = argparse.ArgumentParser()
    ap.add_argument("--only-sut", help="run only this SUT id (S0..S5)")
    ap.add_argument("--only-runner", help="run only this runner id")
    ap.add_argument("--skip-run", action="store_true",
                    help="don't run; just aggregate from existing ledgers")
    args = ap.parse_args()

    # 1) Run every (SUT, runner) cell.
    results: dict[str, dict[str, dict]] = {}
    for sut_id, sut_desc, ckpt in SUTS:
        if args.only_sut and sut_id != args.only_sut:
            continue
        if not ckpt.exists():
            print(f"!! {sut_id}: checkpoint missing at {ckpt}")
            continue
        results[sut_id] = {"_desc": sut_desc, "_ckpt_sha256": sha256_of(ckpt)}
        for runner_id, mod, ledger_rel, extras, runner_args in RUNNERS:
            if args.only_runner and runner_id != args.only_runner:
                continue
            rdir = MC / sut_id / runner_id
            manifest = build_manifest(sut_id, ckpt, runner_id, mod,
                                      dict(extras), list(runner_args))
            ledger = rdir / ledger_rel
            if args.skip_run:
                rc, log = 0, "(skipped run)"
            else:
                print(f"== {sut_id} :: {runner_id} ==", flush=True)
                rc, log = run_runner(mod, manifest, runner_args)
            metric = extract_metric(runner_id, ledger)
            metric["returncode"] = rc
            if rc != 0 or not metric.get("ok"):
                metric["log_tail"] = log[-500:]
            results[sut_id][runner_id] = metric

    # 2) Aggregate per-MR distributions and CIs.
    aggregate: dict[str, dict] = {"per_sut": results, "per_mr_aggregates": {}}
    seed_family = ["S0", "S1", "S2", "S3"]

    def numeric_at(sid: str, rid: str, key: str):
        v = results.get(sid, {}).get(rid, {}).get(key)
        return v if isinstance(v, (int, float)) else None

    for rid, scalar_key in [("node_perm", "rel_l2"),
                            ("mirror_ood", "median_rel_l2"),
                            ("mirror_sym", "rel_l2"),
                            ("conservation", "max_ratio"),
                            ("rollout", "median")]:
        seed_vals = [v for v in (numeric_at(s, rid, scalar_key) for s in seed_family)
                     if v is not None]
        m, lo, hi = bootstrap_ci(seed_vals)
        aggregate["per_mr_aggregates"][rid] = {
            "scalar": scalar_key,
            "seed_family_values": seed_vals,
            "seed_family_mean": m,
            "seed_family_ci_lo": lo,
            "seed_family_ci_hi": hi,
            "S4_value": numeric_at("S4", rid, scalar_key),
            "S5_value": numeric_at("S5", rid, scalar_key),
        }
    # Fault detection: per-mutant detection rate across the 6 SUTs.
    fd_per_sut = {s: results.get(s, {}).get("fault_det", {}).get("detection_matrix", {})
                  for s, *_ in SUTS}
    aggregate["per_mr_aggregates"]["fault_det"] = {
        "detection_matrix_per_sut": fd_per_sut,
        "summary_per_sut": {s: results.get(s, {}).get("fault_det", {}).get("summary", {})
                            for s, *_ in SUTS},
    }

    out = MC / "e1_aggregate.json"
    out.write_text(json.dumps(aggregate, indent=2) + "\n", encoding="utf-8")
    print(f"\nwrote {out}")

    # 3) Brief textual summary to stdout.
    print("\n=== E1 per-MR seed-family aggregates (S0..S3 bootstrap 95% CI) ===")
    for rid, info in aggregate["per_mr_aggregates"].items():
        if rid == "fault_det":
            continue
        m, lo, hi = info["seed_family_mean"], info["seed_family_ci_lo"], info["seed_family_ci_hi"]
        s4, s5 = info["S4_value"], info["S5_value"]
        print(f"  {rid:14s} mean={m:.4g} CI=[{lo:.4g}, {hi:.4g}] "
              f"S4={s4} S5={s5}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
